spring.application.name=authservice

spring.datasource.url=jdbc:postgresql://localhost:5432/auth-vallesol_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

application.security.jwt.secret-key=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aFNlcnZpY2UxMjM0NTY=
application.security.jwt.expiration=86400000

server.port=8080

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.docker.compose.enabled=false